/*
clase para manejar las sugerencias del buscador
*/
class ListHerosSuggestion {
  static List<String> listHeros = [
    'Spider-Man',
    'Iron Man',
    'Batman',
    'Superman',
    'Wonder Woman',
    'Captain America',
    'Thor',
    'Hulk',
    'Black Widow',
    'Wolverine',
    'Deadpool',
    'Green Lantern',
    'The Flash',
    'Aquaman',
    'Doctor Strange',
    'Black Panther',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'The Wasp',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Punisher',
    'Ghost Rider',
    'Silver Surfer',
    'Captain Marvel',
    'Shazam',
    'Green Arrow',
    'Martian Manhunter',
    'Cyborg',
    'Nightwing',
    'Starfire',
    'Raven',
    'Beast Boy',
    'Robin',
    'Batgirl',
    'Supergirl',
    'Harley Quinn',
    'Catwoman',
    'The Joker',
    'Lex Luthor',
    'Riddler',
    'Two-Face',
    'Bane',
    'Poison Ivy',
    'Mr. Freeze',
    'Scarecrow',
    'Penguin',
    'Black Adam',
    'Reverse-Flash',
    'Sinestro',
    'Zatanna',
    'John Constantine',
    'Swamp Thing',
    'Blue Beetle',
    'Booster Gold',
    'Static Shock',
    'Black Canary',
    'Hawkman',
    'Hawkgirl',
    'Green Goblin',
    'Doctor Octopus',
    'Sandman',
    'Venom',
    'Carnage',
    'Kingpin',
    'Electro',
    'Mysterio',
    'Lizard',
    'Rhino',
    'Kraven the Hunter',
    'Vulture',
    'Chameleon',
    'Shocker',
    'Scorpion',
    'Taskmaster',
    'Red Skull',
    'Baron Zemo',
    'Winter Soldier',
    'Falcon',
    'War Machine',
    'Star-Lord',
    'Gamora',
    'Drax the Destroyer',
    'Rocket Raccoon',
    'Groot',
    'Nebula',
    'Yondu',
    'Ronan the Accuser',
    'Thanos',
    'Galactus',
    'Apocalypse',
    'Magneto',
    'Mystique',
    'Quicksilver',
    'Storm',
    'Cyclops',
    'Jean Grey',
    'Moon Knight',
    'Mantis',
    'Groot',
    'Nebula',
    'Yondu',
    'Ronan the Accuser',
    'Thanos',
    'Galactus',
    'Apocalypse',
    'Magneto',
    'Mystique',
    'Quicksilver',
    'Storm',
    'Cyclops',
    'Jean Grey',
    'Nightcrawler',
    'Gambit',
    'Rogue',
    'Iceman',
    'Beast',
    'Jubilee',
    'Psylocke',
    'Angel',
    'Emma Frost',
    'Sabretooth',
    'Toad',
    'Blob',
    'Mimic',
    'Madrox',
    'Omega Red',
    'Havok',
    'Polaris',
    'Shadowcat',
    'Wolfsbane',
    'Siryn',
    'Marrow',
    'Skin',
    'Maggott',
    'Adam Warlock',
    'Mantis',
    'Black Bolt',
    'Medusa',
    'Crystal',
    'Karnak',
    'Gorgon',
    'Lockjaw',
    'Quicksilver',
    'Sentry',
    'Hyperion',
    'Nighthawk',
    'Dr. Voodoo',
    'Black Knight',
    'Cloak',
    'Dagger',
    'The Inhumans',
    'Sif',
    'Fandral',
    'Hogun',
    'Volstagg',
    'Beta Ray Bill',
    'Ego the Living Planet',
    'The Living Tribunal',
    'Infinity',
    'The Watcher',
    'Uatu',
    'Korg',
    'Miek',
    'Sif',
    'Hela',
    'Malekith',
    'The Collector',
    'The Grandmaster',
    'Ronin',
    'Ka-Zar',
    'Shanna the She-Devil',
    'Sasquatch',
    'Puck',
    'Snowbird',
    'Northstar',
    'Aurora',
    'M',
    'Jubilee',
    'Sunfire',
    'X-Man',
    'Nate Grey',
    'Madeline Pryor',
    'Marauders',
    'Marauder',
    'Deathbird',
    'The Brood',
    'The Shiar',
    'Warpath',
    'Thunderbird',
    'Skin',
    'Maggott',
    'Adam X',
    'Marrow',
    'Mondo',
    'Fantomex',
    'E.V.A.',
    'Husk',
    'Elixir',
    'Cannonball',
    'Sunspot',
    'M',
    'Dust',
    'Bling!',
    'X-23',
    'Logan',
    'Laura Kinney',
    'Wolverine',
    'Daken',
    'Lady Deathstrike',
    'Omega Red',
    'Sauron',
    'The Red Onslaught',
    'Gorgon',
    'Shang-Chi',
    'Wu Xiu',
    'Iron Fist',
    'Mantis',
    'Karnak',
    'Gorgon',
    'Medusa',
    'Crystal',
    'Inferno',
    'Luna Snow',
    'Sentry',
    'Hyperion',
    'Thor',
    'Loki',
    'Baldur',
    'Hela',
    'Angela',
    'Valkyrie',
    'Hela',
    'Frigga',
    'Sif',
    'Volstagg',
    'Fandral',
    'Hogun',
    'Beta Ray Bill',
    'Skurge',
    'The Enchantress',
    'Amora',
    'Lorelei',
    'Hela',
    'Cul',
    'Ragnarok',
    'Fenris',
    'Jormungand',
    'Surtur',
    'Jormungand',
    'Ymir',
    'Frost Giants',
    'The Serpent',
    'Ego',
    'Galactus',
    'Silver Surfer',
    'Nova',
    'Drax',
    'Star-Lord',
    'Gamora',
    'Nebula',
    'Yondu',
    'Ronan',
    'Kree',
    'Skrull',
    'Shiar',
    'Inhumans',
    'Maximus',
    'Black Bolt',
    'Medusa',
    'Crystal',
    'Karnak',
    'Gorgon',
    'Lockjaw',
    'Quicksilver',
    'Monarch',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Ayo',
    'M’Baku',
    'Nakia',
    'W’Kabi',
    'Ramonda',
    'Moses Magnum',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku',
    'Ramonda',
    'Namor',
    'Doctor Doom',
    'Victor Von Doom',
    'Galactus',
    'Dr. Strange',
    'Wong',
    'Clea',
    'The Ancient One',
    'Baron Mordo',
    'Dormammu',
    'Nightmare',
    'Shuma-Gorath',
    'Satana',
    'Mordo',
    'Topaz',
    'Hela',
    'Plague',
    'Satana',
    'Damian Hellstrom',
    'The Defenders',
    'Hellcat',
    'Nighthawk',
    'Moon Knight',
    'The Punisher',
    'Daredevil',
    'Luke Cage',
    'Jessica Jones',
    'Iron Fist',
    'The Avengers',
    'Thor',
    'Hawkeye',
    'Scarlet Witch',
    'Vision',
    'Ant-Man',
    'Wasp',
    'Black Widow',
    'Iron Man',
    'Captain America',
    'Hulk',
    'Doctor Strange',
    'Wanda Maximoff',
    'Steve Rogers',
    'Natasha Romanoff',
    'Clint Barton',
    'Peter Parker',
    'Tony Stark',
    'Bruce Banner',
    'Sam Wilson',
    'Bucky Barnes',
    'Wanda Maximoff',
    'Pietro Maximoff',
    'War Machine',
    'Black Panther',
    'Shuri',
    'Okoye',
    'Nakia',
    'M’Baku'
  ];
}
